CREATE SCHEMA IF NOT EXISTS game;
CREATE SCHEMA IF NOT EXISTS settings;
CREATE SCHEMA IF NOT EXISTS logs;

GRANT USAGE ON SCHEMA game TO ws_world_dev;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA game
TO ws_world_dev;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA game
TO ws_world_dev;

ALTER DEFAULT PRIVILEGES IN SCHEMA game
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ws_world_dev;

ALTER DEFAULT PRIVILEGES IN SCHEMA game
GRANT USAGE, SELECT ON SEQUENCES TO ws_world_dev;

GRANT USAGE ON SCHEMA logs TO ws_world_dev;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA logs
TO ws_world_dev;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA logs
TO ws_world_dev;

ALTER DEFAULT PRIVILEGES IN SCHEMA logs
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ws_world_dev;

ALTER DEFAULT PRIVILEGES IN SCHEMA logs
GRANT USAGE, SELECT ON SEQUENCES TO ws_world_dev;