services:

  auth-server:
    restart: always
    build:
      context: ./backend
      dockerfile: cmd/auth_server/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  game-server:
    restart: always
    build:
      context: ./backend
      dockerfile: cmd/game_server/Dockerfile
    ports:
      - "4001:4000"
    depends_on:
      - auth-server
      - postgres
      - redis
    networks:
      - app-network

  game-hub:
    restart: always
    build:
      context: ./backend
      dockerfile: cmd/game_hub/Dockerfile
    ports:
      - "4002:4000"
    depends_on:
      - auth-server
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: