services:
  frontend:
    restart: always
    build: 
      context: ./frontend
      args:
        VITE_AUTH_URL: ${VITE_AUTH_URL}
        VITE_HUB_URL: ${VITE_HUB_URL}
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - VITE_AUTH_URL=${VITE_AUTH_URL}
      - VITE_HUB_URL=${VITE_HUB_URL}
    depends_on:
      - hub
    networks:
      - app-network

  auth:
    restart: always
    build:
      context: ./backend
      dockerfile: cmd/auth_server/Dockerfile
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
      - DOCKER_AUTH=${DOCKER_AUTH}
      - DOCKER_HUB=${DOCKER_HUB}
      - DOCKER_TOKEN=${DOCKER_TOKEN}
      - SERVER_PORT=${AUTH_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=auth
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - USER_AGENT=auth
    depends_on:
      - postgres
    networks:
      - app-network

  hub:
    restart: always
    build:
      context: ./backend
      dockerfile: cmd/game_hub/Dockerfile
    ports:
      - "${HUB_PORT}:${HUB_PORT}"
    environment:
      - DOCKER_AUTH=${DOCKER_AUTH}
      - DOCKER_HUB=${DOCKER_HUB}
      - DOCKER_TOKEN=${DOCKER_TOKEN}
      - SERVER_PORT=${HUB_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=hub
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - USER_AGENT=hub
    depends_on:
      - auth
    networks:
      - app-network

  game-realm-1:
    restart: always
    build:
      context: ./backend
      dockerfile: cmd/game_server/Dockerfile
    ports:
      - "4001:${REALM_PORT}"
    environment:
      - REALM_NAME=Realm1
      - PUBLIC_ENDPOINT=localhost:4001
      - DOCKER_AUTH=${DOCKER_AUTH}
      - DOCKER_HUB=${DOCKER_HUB}
      - DOCKER_TOKEN=${DOCKER_TOKEN}
      - SERVER_PORT=${REALM_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=realm1
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - USER_AGENT=game-realm-1
    depends_on:
      - hub
    networks:
      - app-network

  game-realm-2:
    restart: always
    build:
      context: ./backend
      dockerfile: cmd/game_server/Dockerfile
    ports:
      - "4002:${REALM_PORT}"
    environment:
      - REALM_NAME=Realm2
      - PUBLIC_ENDPOINT=localhost:4002
      - DOCKER_AUTH=${DOCKER_AUTH}
      - DOCKER_HUB=${DOCKER_HUB}
      - DOCKER_TOKEN=${DOCKER_TOKEN}
      - SERVER_PORT=${REALM_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=realm2
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - USER_AGENT=game-realm-2
    depends_on:
      - hub
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: