CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS logs;

GRANT USAGE ON SCHEMA auth TO as_auth;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA auth
TO as_auth;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA auth
TO as_auth;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO as_auth;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth
GRANT USAGE, SELECT ON SEQUENCES TO as_auth;

GRANT USAGE ON SCHEMA logs TO as_auth;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA logs
TO as_auth;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA logs
TO as_auth;

ALTER DEFAULT PRIVILEGES IN SCHEMA logs
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO as_auth;

ALTER DEFAULT PRIVILEGES IN SCHEMA logs
GRANT USAGE, SELECT ON SEQUENCES TO as_auth;