CREATE SCHEMA IF NOT EXISTS game;
CREATE SCHEMA IF NOT EXISTS settings;
CREATE SCHEMA IF NOT EXISTS logs;

GRANT USAGE ON SCHEMA game TO rs_realm_dev;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA game
TO rs_realm_dev;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA game
TO rs_realm_dev;

ALTER DEFAULT PRIVILEGES IN SCHEMA game
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rs_realm_dev;

ALTER DEFAULT PRIVILEGES IN SCHEMA game
GRANT USAGE, SELECT ON SEQUENCES TO rs_realm_dev;

GRANT USAGE ON SCHEMA logs TO rs_realm_dev;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA logs
TO rs_realm_dev;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA logs
TO rs_realm_dev;

ALTER DEFAULT PRIVILEGES IN SCHEMA logs
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rs_realm_dev;

ALTER DEFAULT PRIVILEGES IN SCHEMA logs
GRANT USAGE, SELECT ON SEQUENCES TO rs_realm_dev;