CREATE SCHEMA IF NOT EXISTS game;
CREATE SCHEMA IF NOT EXISTS logs;

GRANT USAGE ON SCHEMA game TO app_user;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA game
TO app_user;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA game
TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA game
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA game
GRANT USAGE, SELECT ON SEQUENCES TO app_user;

GRANT USAGE ON SCHEMA logs TO app_user;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA logs
TO app_user;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA logs
TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA logs
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA logs
GRANT USAGE, SELECT ON SEQUENCES TO app_user;