name: SimplifiedCrafter
services:
  mysql_database:
    build: ../database
    container_name: mysql_database
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    container_name: backend
    build: ../csharp/Backend
    env_file:
      - .env
    ports:
      - "${BACKEND_HTTP_PORT}:${BACKEND_HTTP_PORT}"
      - "${BACKEND_HTTPS_PORT}:${BACKEND_HTTPS_PORT}"
    depends_on:
      - mysql_database

volumes:
  mysql_data: