name: SimplifiedCrafter
services:
  mysql_database:
    build: ../database
    container_name: mysql_database
    restart: always
    env_file:
      - .env
    expose:
      - ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    container_name: backend
    build: 
      context: ../csharp
      dockerfile: ../csharp/Backend/Dockerfile
    env_file:
      - .env
    expose:
      - ${BACKEND_HTTP_PORT}
    ports:
      - "${BACKEND_HTTP_PORT}:${BACKEND_HTTP_PORT}"
    depends_on:
      - mysql_database

volumes:
  mysql_data: