services:
  mysql_database:
    build: ../database
    image: mysql_database
    container_name: mysql_database
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: backend
    container_name: backend
    build: ../csharp/Backend
    env_file:
      - .env

volumes:
  mysql_data: