name: SimplifiedCrafter
services:
  mysql_database:
    build: ../database
    container_name: mysql_database
    restart: always
    env_file:
      - .env
    expose:
      - ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    container_name: backend
    build: 
      context: ../csharp
      dockerfile: ../csharp/Backend/Dockerfile
    env_file:
      - .env
    expose:
      - ${BACKEND_HTTP_PORT}
    ports:
      - "${BACKEND_HTTP_PORT}:${BACKEND_HTTP_PORT}"
    volumes:
      - /var/log/SimplifiedCrafter:/var/log
    depends_on:
      - mysql_database

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./logging/loki-config.yml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log/SimplifiedCrafter:/var/log
      - ./logging/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./logging/grafana/provisioning:/etc/grafana/provisioning

volumes:
  mysql_data:
  grafana_data: