name: simplified_crafter
services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "${LOKI_PORT}:${LOKI_PORT}"
    volumes:
      - ./logging/loki-config.yml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log/SimplifiedCrafter:/var/log
      - ./logging/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./logging/grafana/provisioning:/etc/grafana/provisioning

  game-ui:
    restart: always
    build: ./ui/game
    ports:
      - "3000:3000"
    depends_on:
      - game-server
    networks:
      - app-network

  hub-ui:
    restart: always
    build: ./ui/hub
    ports:
      - "3001:3000"
    depends_on:
      - game-hub
    networks:
      - app-network

volumes:
  mysql_data:
  grafana_data:
